# Entrenamiento de alta calidad (6â€“10 horas)

total_steps: 1000000

n_envs: 4

policy_net:
  layers: [128, 128]

dqn:
  learning_rate: 0.0005
  gamma: 0.98
  buffer_size: 200000
  learning_starts: 2000
  batch_size: 128
  train_freq: 4
  gradient_steps: 2
  n_steps: 4
  target_update_interval: 250

exploration:
  fraction: 0.40
  initial_eps: 1.0
  final_eps: 0.05
